package com.system.mapper;

import com.system.dto.ProyectoDTO;
import com.system.dto.ProyectoCompletoDTO;
import com.system.entity.Proyecto;
import com.system.entity.id.ProyectoId;
import org.mapstruct.*;
import java.math.BigDecimal;

@Mapper(componentModel = "spring", imports = {BigDecimal.class, ProyectoId.class})
public interface ProyectoMapper {
    @Mapping(target = "id", expression = "java(new ProyectoId(dto.getCodCia(), dto.getCodPyto()))")
    @Mapping(target = "nombPyto", source = "nombPyto")
    @Mapping(target = "emplJefeProy", source = "emplJefeProy")
    @Mapping(target = "codCia1", source = "codCia1")
    @Mapping(target = "ciaContrata", source = "ciaContrata")
    @Mapping(target = "codCC", source = "codCC")
    @Mapping(target = "codCliente", source = "codCliente")
    @Mapping(target = "flgEmpConsorcio", source = "flgEmpConsorcio")
    @Mapping(target = "codSNIP", source = "codSNIP")
    @Mapping(target = "fecReg", expression = "java(dto.getFecReg() != null ? dto.getFecReg().toLocalDate() : null)")
    @Mapping(target = "codFase", source = "codFase")
    @Mapping(target = "codNivel", source = "codNivel")
    @Mapping(target = "codFuncion", source = "codFuncion")
    @Mapping(target = "codSituacion", source = "codSituacion")
    @Mapping(target = "numInfor", source = "numInfor")
    @Mapping(target = "numInforEntrg", source = "numInforEntrg")
    @Mapping(target = "estPyto", source = "estPyto")
    @Mapping(target = "fecEstado", expression = "java(dto.getFecEstado() != null ? dto.getFecEstado().toLocalDate() : null)")
    @Mapping(target = "valRefer", expression = "java(dto.getValRefer() != null ? BigDecimal.valueOf(dto.getValRefer()) : null)")
    @Mapping(target = "costoDirecto", expression = "java(dto.getCostoDirecto() != null ? BigDecimal.valueOf(dto.getCostoDirecto()) : null)")
    @Mapping(target = "costoGGen", expression = "java(dto.getCostoGGen() != null ? BigDecimal.valueOf(dto.getCostoGGen()) : null)")
    @Mapping(target = "costoFinan", expression = "java(dto.getCostoFinan() != null ? BigDecimal.valueOf(dto.getCostoFinan()) : null)")
    @Mapping(target = "impUtilidad", expression = "java(dto.getImpUtilidad() != null ? BigDecimal.valueOf(dto.getImpUtilidad()) : null)")
    @Mapping(target = "costoTotSinIGV", expression = "java(dto.getCostoTotSinIGV() != null ? BigDecimal.valueOf(dto.getCostoTotSinIGV()) : null)")
    @Mapping(target = "impIGV", expression = "java(dto.getImpIGV() != null ? BigDecimal.valueOf(dto.getImpIGV()) : null)")
    @Mapping(target = "costoTotal", expression = "java(dto.getCostoTotal() != null ? BigDecimal.valueOf(dto.getCostoTotal()) : null)")
    @Mapping(target = "costoPenalid", expression = "java(dto.getCostoPenalid() != null ? BigDecimal.valueOf(dto.getCostoPenalid()) : null)")
    @Mapping(target = "codDpto", source = "codDpto")
    @Mapping(target = "codProv", source = "codProv")
    @Mapping(target = "codDist", source = "codDist")
    @Mapping(target = "fecViab", expression = "java(dto.getFecViab() != null ? dto.getFecViab().toLocalDate() : null)")
    @Mapping(target = "rutaDoc", source = "rutaDoc")
    @Mapping(target = "annoIni", source = "annoIni")
    @Mapping(target = "annoFin", source = "annoFin")
    @Mapping(target = "codObjC", source = "codObjC")
    @Mapping(target = "logoProy", source = "logoProy")
    @Mapping(target = "tabEstado", source = "tabEstado")
    @Mapping(target = "codEstado", source = "codEstado")
    @Mapping(target = "observac", source = "observac")
    @Mapping(target = "vigente", source = "vigente")
    @Mapping(target = "cia", ignore = true)
    Proyecto toEntity(ProyectoDTO dto);

    @Mapping(target = "codCia", expression = "java(entity.getId() != null ? entity.getId().getCodCia() : null)")
    @Mapping(target = "codPyto", expression = "java(entity.getId() != null ? entity.getId().getCodPyto() : null)")
    @Mapping(target = "nombPyto", source = "nombPyto")
    @Mapping(target = "emplJefeProy", source = "emplJefeProy")
    @Mapping(target = "codCia1", source = "codCia1")
    @Mapping(target = "ciaContrata", source = "ciaContrata")
    @Mapping(target = "codCC", source = "codCC")
    @Mapping(target = "codCliente", source = "codCliente")
    @Mapping(target = "flgEmpConsorcio", source = "flgEmpConsorcio")
    @Mapping(target = "codSNIP", source = "codSNIP")
    @Mapping(target = "fecReg", expression = "java(entity.getFecReg() != null ? java.sql.Date.valueOf(entity.getFecReg()) : null)")
    @Mapping(target = "codFase", source = "codFase")
    @Mapping(target = "codNivel", source = "codNivel")
    @Mapping(target = "codFuncion", source = "codFuncion")
    @Mapping(target = "codSituacion", source = "codSituacion")
    @Mapping(target = "numInfor", source = "numInfor")
    @Mapping(target = "numInforEntrg", source = "numInforEntrg")
    @Mapping(target = "estPyto", source = "estPyto")
    @Mapping(target = "fecEstado", expression = "java(entity.getFecEstado() != null ? java.sql.Date.valueOf(entity.getFecEstado()) : null)")
    @Mapping(target = "valRefer", expression = "java(entity.getValRefer() != null ? entity.getValRefer().doubleValue() : null)")
    @Mapping(target = "costoDirecto", expression = "java(entity.getCostoDirecto() != null ? entity.getCostoDirecto().doubleValue() : null)")
    @Mapping(target = "costoGGen", expression = "java(entity.getCostoGGen() != null ? entity.getCostoGGen().doubleValue() : null)")
    @Mapping(target = "costoFinan", expression = "java(entity.getCostoFinan() != null ? entity.getCostoFinan().doubleValue() : null)")
    @Mapping(target = "impUtilidad", expression = "java(entity.getImpUtilidad() != null ? entity.getImpUtilidad().doubleValue() : null)")
    @Mapping(target = "costoTotSinIGV", expression = "java(entity.getCostoTotSinIGV() != null ? entity.getCostoTotSinIGV().doubleValue() : null)")
    @Mapping(target = "impIGV", expression = "java(entity.getImpIGV() != null ? entity.getImpIGV().doubleValue() : null)")
    @Mapping(target = "costoTotal", expression = "java(entity.getCostoTotal() != null ? entity.getCostoTotal().doubleValue() : null)")
    @Mapping(target = "costoPenalid", expression = "java(entity.getCostoPenalid() != null ? entity.getCostoPenalid().doubleValue() : null)")
    @Mapping(target = "codDpto", source = "codDpto")
    @Mapping(target = "codProv", source = "codProv")
    @Mapping(target = "codDist", source = "codDist")
    @Mapping(target = "fecViab", expression = "java(entity.getFecViab() != null ? java.sql.Date.valueOf(entity.getFecViab()) : null)")
    @Mapping(target = "rutaDoc", source = "rutaDoc")
    @Mapping(target = "annoIni", source = "annoIni")
    @Mapping(target = "annoFin", source = "annoFin")
    @Mapping(target = "codObjC", source = "codObjC")
    @Mapping(target = "logoProy", source = "logoProy")
    @Mapping(target = "tabEstado", source = "tabEstado")
    @Mapping(target = "codEstado", source = "codEstado")
    @Mapping(target = "observac", source = "observac")
    @Mapping(target = "vigente", source = "vigente")
    ProyectoDTO toDTO(Proyecto entity);

    @BeanMapping(nullValuePropertyMappingStrategy = NullValuePropertyMappingStrategy.IGNORE)
    @Mapping(target = "id", expression = "java(new ProyectoId(dto.getCodCia(), dto.getCodPyto()))")
    @Mapping(target = "nombPyto", source = "nombPyto")
    @Mapping(target = "emplJefeProy", source = "emplJefeProy")
    @Mapping(target = "codCia1", source = "codCia1")
    @Mapping(target = "ciaContrata", source = "ciaContrata")
    @Mapping(target = "codCC", source = "codCC")
    @Mapping(target = "codCliente", source = "codCliente")
    @Mapping(target = "flgEmpConsorcio", source = "flgEmpConsorcio")
    @Mapping(target = "codSNIP", source = "codSNIP")
    @Mapping(target = "fecReg", expression = "java(dto.getFecReg() != null ? dto.getFecReg().toLocalDate() : null)")
    @Mapping(target = "codFase", source = "codFase")
    @Mapping(target = "codNivel", source = "codNivel")
    @Mapping(target = "codFuncion", source = "codFuncion")
    @Mapping(target = "codSituacion", source = "codSituacion")
    @Mapping(target = "numInfor", source = "numInfor")
    @Mapping(target = "numInforEntrg", source = "numInforEntrg")
    @Mapping(target = "estPyto", source = "estPyto")
    @Mapping(target = "fecEstado", expression = "java(dto.getFecEstado() != null ? dto.getFecEstado().toLocalDate() : null)")
    @Mapping(target = "valRefer", expression = "java(dto.getValRefer() != null ? BigDecimal.valueOf(dto.getValRefer()) : null)")
    @Mapping(target = "costoDirecto", expression = "java(dto.getCostoDirecto() != null ? BigDecimal.valueOf(dto.getCostoDirecto()) : null)")
    @Mapping(target = "costoGGen", expression = "java(dto.getCostoGGen() != null ? BigDecimal.valueOf(dto.getCostoGGen()) : null)")
    @Mapping(target = "costoFinan", expression = "java(dto.getCostoFinan() != null ? BigDecimal.valueOf(dto.getCostoFinan()) : null)")
    @Mapping(target = "impUtilidad", expression = "java(dto.getImpUtilidad() != null ? BigDecimal.valueOf(dto.getImpUtilidad()) : null)")
    @Mapping(target = "costoTotSinIGV", expression = "java(dto.getCostoTotSinIGV() != null ? BigDecimal.valueOf(dto.getCostoTotSinIGV()) : null)")
    @Mapping(target = "impIGV", expression = "java(dto.getImpIGV() != null ? BigDecimal.valueOf(dto.getImpIGV()) : null)")
    @Mapping(target = "costoTotal", expression = "java(dto.getCostoTotal() != null ? BigDecimal.valueOf(dto.getCostoTotal()) : null)")
    @Mapping(target = "costoPenalid", expression = "java(dto.getCostoPenalid() != null ? BigDecimal.valueOf(dto.getCostoPenalid()) : null)")
    @Mapping(target = "codDpto", source = "codDpto")
    @Mapping(target = "codProv", source = "codProv")
    @Mapping(target = "codDist", source = "codDist")
    @Mapping(target = "fecViab", expression = "java(dto.getFecViab() != null ? dto.getFecViab().toLocalDate() : null)")
    @Mapping(target = "rutaDoc", source = "rutaDoc")
    @Mapping(target = "annoIni", source = "annoIni")
    @Mapping(target = "annoFin", source = "annoFin")
    @Mapping(target = "codObjC", source = "codObjC")
    @Mapping(target = "logoProy", source = "logoProy")
    @Mapping(target = "tabEstado", source = "tabEstado")
    @Mapping(target = "codEstado", source = "codEstado")
    @Mapping(target = "observac", source = "observac")
    @Mapping(target = "vigente", source = "vigente")
    @Mapping(target = "cia", ignore = true)
    void updateEntityFromDTO(ProyectoDTO dto, @MappingTarget Proyecto entity);

    // Entidad -> DTO Completo (sin las listas, se agregan en el service)
    @Mapping(target = "codCia", expression = "java(entity.getId() != null ? entity.getId().getCodCia() : null)")
    @Mapping(target = "codPyto", expression = "java(entity.getId() != null ? entity.getId().getCodPyto() : null)")
    @Mapping(target = "nombPyto", source = "nombPyto")
    @Mapping(target = "emplJefeProy", source = "emplJefeProy")
    @Mapping(target = "codCia1", source = "codCia1")
    @Mapping(target = "ciaContrata", source = "ciaContrata")
    @Mapping(target = "codCC", source = "codCC")
    @Mapping(target = "codCliente", source = "codCliente")
    @Mapping(target = "flgEmpConsorcio", source = "flgEmpConsorcio")
    @Mapping(target = "codSNIP", source = "codSNIP")
    @Mapping(target = "fecReg", expression = "java(entity.getFecReg() != null ? java.sql.Date.valueOf(entity.getFecReg()) : null)")
    @Mapping(target = "codFase", source = "codFase")
    @Mapping(target = "codNivel", source = "codNivel")
    @Mapping(target = "codFuncion", source = "codFuncion")
    @Mapping(target = "codSituacion", source = "codSituacion")
    @Mapping(target = "numInfor", source = "numInfor")
    @Mapping(target = "numInforEntrg", source = "numInforEntrg")
    @Mapping(target = "estPyto", source = "estPyto")
    @Mapping(target = "fecEstado", expression = "java(entity.getFecEstado() != null ? java.sql.Date.valueOf(entity.getFecEstado()) : null)")
    @Mapping(target = "valRefer", expression = "java(entity.getValRefer() != null ? entity.getValRefer().doubleValue() : null)")
    @Mapping(target = "costoDirecto", expression = "java(entity.getCostoDirecto() != null ? entity.getCostoDirecto().doubleValue() : null)")
    @Mapping(target = "costoGGen", expression = "java(entity.getCostoGGen() != null ? entity.getCostoGGen().doubleValue() : null)")
    @Mapping(target = "costoFinan", expression = "java(entity.getCostoFinan() != null ? entity.getCostoFinan().doubleValue() : null)")
    @Mapping(target = "impUtilidad", expression = "java(entity.getImpUtilidad() != null ? entity.getImpUtilidad().doubleValue() : null)")
    @Mapping(target = "costoTotSinIGV", expression = "java(entity.getCostoTotSinIGV() != null ? entity.getCostoTotSinIGV().doubleValue() : null)")
    @Mapping(target = "impIGV", expression = "java(entity.getImpIGV() != null ? entity.getImpIGV().doubleValue() : null)")
    @Mapping(target = "costoTotal", expression = "java(entity.getCostoTotal() != null ? entity.getCostoTotal().doubleValue() : null)")
    @Mapping(target = "costoPenalid", expression = "java(entity.getCostoPenalid() != null ? entity.getCostoPenalid().doubleValue() : null)")
    @Mapping(target = "codDpto", source = "codDpto")
    @Mapping(target = "codProv", source = "codProv")
    @Mapping(target = "codDist", source = "codDist")
    @Mapping(target = "fecViab", expression = "java(entity.getFecViab() != null ? java.sql.Date.valueOf(entity.getFecViab()) : null)")
    @Mapping(target = "rutaDoc", source = "rutaDoc")
    @Mapping(target = "annoIni", source = "annoIni")
    @Mapping(target = "annoFin", source = "annoFin")
    @Mapping(target = "codObjC", source = "codObjC")
    @Mapping(target = "logoProy", source = "logoProy")
    @Mapping(target = "tabEstado", source = "tabEstado")
    @Mapping(target = "codEstado", source = "codEstado")
    @Mapping(target = "observac", source = "observac")
    @Mapping(target = "vigente", source = "vigente")
    @Mapping(target = "cliente", ignore = true) // Se asigna manualmente en el service
    @Mapping(target = "empleados", ignore = true) // Se asigna en el service
    @Mapping(target = "proveedores", ignore = true) // Se asigna en el service
    ProyectoCompletoDTO toCompletoDTO(Proyecto entity);
}
